---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
  labels:
    app: echoserver
    app.kubernetes.io/name: echoserver
    app.kubernetes.io/part-of: echoserver
spec:
  selector:
    app.kubernetes.io/name: echoserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
