---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: folder-alloy
spec:
  instanceSelector:
    matchLabels:
      # dashboards: "grafana"
      app.kubernetes.io/instance: {{ .Values.namespaceOverride | default .Release.Name }}
      app.kubernetes.io/name: grafana
  title: alloy
