---

## Configuration for the kube-prometheus-stack dependency
## <https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml>
kube-prometheus-stack:
  grafana:
    adminUser: admin
    adminPassword: admin
