---
## Provide a name in place of kube-prometheus-stack for `app:` labels
##
namespaceOverride: &namespaceOverride "monitoring"

## Configuration for the kube-prometheus-stack dependency
## <https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml>
##
kube-prometheus-stack:
  namespaceOverride: *namespaceOverride

  grafana:
    adminUser: admin
    adminPassword: admin
